### PR TITLE
Code analysis.

### PR DESCRIPTION
**Pull request by idgserpro**

### CODE REVIEW

**Comment by idgserpro** [comment]
@hvelarde The same correction made in https://github.com/plonegovbr/brasil.gov.vcge/pull/40 was made here (https://www.python.org/dev/peps/pep-0257/#one-line-docstrings).

**Comment by hvelarde** [comment]
isn't this a duplicate of #40?

**Comment by idgserpro** [comment]
One is for 1.x, other for master.

**Comment by hvelarde** [comment]
do you mind to do the same I did in the other branch then?

**Comment by idgserpro** [comment]
> do you mind to do the same I did in the other branch then?

What you mean? All the suggestions you gave in the other branch we implemented here.

**Pull request merged**
